### transforming the code into idiomatic python 
  
  
 - replace traditional index manupulation with python core looping idiomatic

In [2]:
# looping over a range number-traditional approach
for i in[0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [3]:
# idiomatic programming 
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

 ### looping over a collection

In [7]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [8]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### looping backwards

In [11]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [12]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

### looping in sorted list

In [14]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [13]:
colors = ['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

###

- if x<=y and y<=z:
- if x<=y<=z:
- if x==True:
- if x:

### pandas


In [15]:
import pandas as pd

In [22]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','c','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [23]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          c      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [25]:
import os

os.chdir("C:\Users\Apashyampakkirikiri\Desktop\jupyter")

In [42]:
mydt.to_csv('workingfile.csv',index = False)

In [37]:
cd desktop

[WinError 2] The system cannot find the file specified: 'desktop'
C:\Users\Apashyampakkirikiri\Desktop\jupyter


### reading the data from csv file

In [48]:
mydata = pd.read_csv('workingfile.csv')

In [47]:
print(mydata)

  custid        name  company  address
0     Id  first_name  company  address
1     11           A       aa      Hyd
2     12           B       bb      Hyd
3     13           c       cc      Hyd
4     14           D       dd      Hyd
5     15           E       ee      Hyd


In [49]:
mydata1 = pd.read_csv('workingfile.csv',names=["custid","name","company","address"])

In [51]:
print(mydata1)

NameError: name 'mydata1' is not defined

### numpy package

 - numpy arrays are bit like python list
 - numpy is also one of the data structure
 - numpy short name for "numeric python" and "numerical python"

In [52]:
import numpy as np

In [54]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [55]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [56]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [58]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
